apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario-app-green
  namespace: inventario-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventario
      version: green # Etiqueta clave
  template:
    metadata:
      labels:
        app: inventario
        version: green
    spec:
      containers:
      - name: inventario-container
        image: ghcr.io/scomygod/inventario-app:latest # Tu nueva imagen
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: APP_COLOR
          value: "green"
        - name: APP_VERSION
          value: "v2"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: API_KEY
        - name: STARTUP_DELAY_SECONDS
          value: "30"
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          periodSeconds: 5
          failureThreshold: 12
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 10
