apiVersion: v1
kind: Service
metadata:
  name: inventario-service
  namespace: inventario-lab
spec:
  type: NodePort
  selector:
    app: inventario
    track: base
  ports:
    - port: 80
      targetPort: 3000
